// components/Footer.vue
<template>
    <footer class=" mx-auto py-8 border-t-1 border-w  border-t-border w-full font-barlow font-light">
        <div class='flex flex-col items-center  lg:flex-row justify-evenly '>
            <div class='flex flex-col lg:flex-row  gap-5'>
                <ul class="items-stretch">
                    <li class="cursor-pointer">Benzenbergstraße 39 – 47</li>
                    <li class="cursor-pointer">40219 Düsseldorf</li>
                </ul>
                <ul class="items-stretch">
                    <li class="cursor-pointer">Telefon: +49 211 / 749 505 0</li>
                    <li class="cursor-pointer">E-Mail: info@active-value.de</li>
                </ul>
            </div>
            <div class='flex my-4 gap-5 lg:my-0'>
                <div class="hover:text-black">
                    <svg xmlns='http://www.w3.org/2000/svg' width='52' height='52' viewBox='0 0 52 52'
                         class="cursor-pointer hover:stroke-yellow-300 hover:fill-yellow-300">
                        <g fill='none' fill-rule='evenodd'>
                            <circle cx='25' cy='25' r='25' fill='#FFF' stroke='#AFB3B6'
                                    class="hover:stroke-yellow-300"/>
                            <g fill='#AFB3B6'>
                                <path
                                    d='M15.178 11.004c0-2.227-1.79-4.019-4.018-4.02-2.221 0-4.016 1.792-4.017 4.013-.002 2.224 1.788 4.021 4.007 4.022 2.235.002 4.028-1.786 4.028-4.015m-4.016 4.908c-2.715 0-4.914-2.207-4.912-4.931.001-2.687 2.215-4.892 4.91-4.89 2.707.001 4.914 2.21 4.911 4.913-.003 2.702-2.21 4.909-4.909 4.908M16.963 6.09c-.49 0-.891-.4-.892-.888 0-.491.401-.896.893-.897.497-.001.894.404.893.91-.001.48-.405.876-.894.876'
                                    transform='translate(14.286 13.552)'/>
                                <path
                                    d='M11.09 21.243h4.45c.53 0 1.054-.058 1.566-.203 1.162-.33 2.123-.97 2.87-1.923.8-1.024 1.184-2.197 1.184-3.498l-.001-8.985c0-.377-.03-.752-.103-1.123-.212-1.086-.697-2.032-1.47-2.818-1.093-1.113-2.427-1.675-3.985-1.678-3.012-.004-6.023 0-9.034-.001-.353 0-.702.028-1.048.096-1.464.29-2.634 1.045-3.498 2.264-.691.973-1.01 2.068-1.009 3.263.003 2.992 0 5.984.003 8.976 0 .288.017.579.056.864.106.789.377 1.52.804 2.19.607.95 1.426 1.655 2.455 2.11.73.324 1.498.468 2.295.466h4.466zM.005 11.126c0-1.537-.011-3.074.004-4.612.015-1.583.538-2.987 1.561-4.193C2.59 1.118 3.884.381 5.432.098 5.812.028 6.197 0 6.584 0l8.988.001c1.574 0 2.98.493 4.195 1.496 1.178.974 1.93 2.217 2.255 3.717.098.452.143.91.143 1.374-.001 3.042.004 6.085-.003 9.128-.003 1.414-.429 2.697-1.262 3.837-.838 1.15-1.939 1.945-3.288 2.387-.63.207-1.277.311-1.94.312-3.053.001-6.107.007-9.161-.002-1.522-.005-2.881-.498-4.065-1.458-1.134-.92-1.88-2.094-2.244-3.512-.138-.536-.198-1.084-.198-1.637v-4.517z'
                                    transform='translate(14.286 13.552)'/>
                            </g>
                        </g>
                    </svg>
                </div>
                <div>
                    <svg xmlns='http://www.w3.org/2000/svg' width='52' height='52' viewBox='0 0 52 52'
                         class="cursor-pointer hover:stroke-yellow-300">
                        <g fill='none' fill-rule='evenodd'>
                            <g>
                                <g>
                                    <g transform='translate(-293 -860) translate(154 861) translate(140)'>
                                        <circle cx='25' cy='25' r='25' fill='#FFF' stroke='#AFB3B6'
                                                class="hover:stroke-yellow-300"/>
                                        <path fill='#AFB3B6'
                                              d='M22.784 36.563h3.644l.005-12.035h3.408l.346-3.207h-3.08c-.102.004-.327.012-.505-.16-.082-.079-.178-.22-.174-.449.005-.301.009-.603.012-.904.005-.573.012-1.145.034-1.717.026-.68.492-1.22 1.157-1.343.226-.042.496-.085.78-.09.603-.012 1.207-.014 1.812-.01-.005-.922-.004-1.833-.003-2.744v-.467l-3.593.003-.15.032c-.16.033-.32.063-.482.092-.34.062-.66.12-.963.214-.744.231-1.305.699-1.667 1.39-.33.628-.505 1.327-.535 2.134-.033.898-.036 1.817-.038 2.706l-.002.622c0 .09-.001.333-.192.517-.19.183-.441.178-.52.18-.454-.006-.908-.004-1.364-.005h-1.005c.004.82.003 1.63.003 2.44v.772h3.075l-.003 12.03zm4.581.937h-5.541l.005-1.544V25.47h-3.036l-.03-.51c-.005-.061-.008-.114-.008-.167v-1.03c0-.9 0-1.797-.005-2.695 0-.08-.002-.322.186-.505s.44-.176.52-.18c.418.004.837.004 1.256.002.373 0 .747 0 1.121.002l.002-.382c.002-.896.004-1.823.038-2.737.035-.934.25-1.785.64-2.528.483-.92 1.233-1.544 2.229-1.854.36-.112.726-.179 1.079-.243.153-.027.306-.056.458-.087l.308-.056h4.631l-.033.576c-.003.042-.006.083-.007.123v.705c-.001 1-.002 2 .004 2.999 0 .08.002.321-.186.505-.188.182-.438.176-.52.18-.682-.008-1.366-.007-2.047.006-.214.004-.434.04-.62.074-.228.042-.369.214-.379.46-.021.561-.027 1.125-.033 1.69l-.006.566h3.859l-.547 5.08H27.39l-.004 11.357c0 .054-.002.108-.004.162l-.017.517z'/>
                                    </g>
                                </g>
                            </g>
                        </g>
                    </svg>


                </div>
            </div>


            <div>
                <ul class="flex gap-0 flex-col lg:flex-row  text-center lg:gap-5">
                    <li><a href=''>Impressum</a></li>
                    <li><a href=''>Datenschutz</a></li>
                    <li><a href=''>AGB</a></li>
                </ul>
                <div>
                    <p class="text-center md:text-normal">Copyright © 2025 active value GmbH - Alle Rechte
                        vorbehalten.</p>
                </div>
            </div>
        </div>
    </footer>
</template>


<script setup lang="ts">
</script>

// active-value/src/components/footer/Footer.jsx
const Footer = () => {

    return (
        <footer>
            <div>
                <div className='footer_wrapper'>
                    <div className='footer_wrapper_address_contact'>
                        <ul>
                            <li>Benzenbergstraße 39 – 47</li>
                            <li>40219 Düsseldorf</li>
                        </ul>
                        <ul>
                            <li>Telefon: +49 211 / 749 505 0</li>
                            <li>E-Mail: info@active-value.de</li>
                        </ul>
                    </div>


                    <div className='footer_wrapper_social_media_link'>
                        <div>
                            <svg xmlns='http://www.w3.org/2000/svg' width='52' height='52' viewBox='0 0 52 52'>
                                <g fill='none' fill-rule='evenodd'>
                                    <circle cx='25' cy='25' r='25' fill='#FFF' stroke='#AFB3B6'/>
                                    <g fill='#AFB3B6'>
                                        <path
                                            d='M15.178 11.004c0-2.227-1.79-4.019-4.018-4.02-2.221 0-4.016 1.792-4.017 4.013-.002 2.224 1.788 4.021 4.007 4.022 2.235.002 4.028-1.786 4.028-4.015m-4.016 4.908c-2.715 0-4.914-2.207-4.912-4.931.001-2.687 2.215-4.892 4.91-4.89 2.707.001 4.914 2.21 4.911 4.913-.003 2.702-2.21 4.909-4.909 4.908M16.963 6.09c-.49 0-.891-.4-.892-.888 0-.491.401-.896.893-.897.497-.001.894.404.893.91-.001.48-.405.876-.894.876'
                                            transform='translate(14.286 13.552)'/>
                                        <path
                                            d='M11.09 21.243h4.45c.53 0 1.054-.058 1.566-.203 1.162-.33 2.123-.97 2.87-1.923.8-1.024 1.184-2.197 1.184-3.498l-.001-8.985c0-.377-.03-.752-.103-1.123-.212-1.086-.697-2.032-1.47-2.818-1.093-1.113-2.427-1.675-3.985-1.678-3.012-.004-6.023 0-9.034-.001-.353 0-.702.028-1.048.096-1.464.29-2.634 1.045-3.498 2.264-.691.973-1.01 2.068-1.009 3.263.003 2.992 0 5.984.003 8.976 0 .288.017.579.056.864.106.789.377 1.52.804 2.19.607.95 1.426 1.655 2.455 2.11.73.324 1.498.468 2.295.466h4.466zM.005 11.126c0-1.537-.011-3.074.004-4.612.015-1.583.538-2.987 1.561-4.193C2.59 1.118 3.884.381 5.432.098 5.812.028 6.197 0 6.584 0l8.988.001c1.574 0 2.98.493 4.195 1.496 1.178.974 1.93 2.217 2.255 3.717.098.452.143.91.143 1.374-.001 3.042.004 6.085-.003 9.128-.003 1.414-.429 2.697-1.262 3.837-.838 1.15-1.939 1.945-3.288 2.387-.63.207-1.277.311-1.94.312-3.053.001-6.107.007-9.161-.002-1.522-.005-2.881-.498-4.065-1.458-1.134-.92-1.88-2.094-2.244-3.512-.138-.536-.198-1.084-.198-1.637v-4.517z'
                                            transform='translate(14.286 13.552)'/>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <div>
                            <svg xmlns='http://www.w3.org/2000/svg' width='52' height='52' viewBox='0 0 52 52'>
                                <g fill='none' fill-rule='evenodd'>
                                    <g>
                                        <g>
                                            <g transform='translate(-293 -860) translate(154 861) translate(140)'>
                                                <circle cx='25' cy='25' r='25' fill='#FFF' stroke='#AFB3B6'/>
                                                <path fill='#AFB3B6'
                                                      d='M22.784 36.563h3.644l.005-12.035h3.408l.346-3.207h-3.08c-.102.004-.327.012-.505-.16-.082-.079-.178-.22-.174-.449.005-.301.009-.603.012-.904.005-.573.012-1.145.034-1.717.026-.68.492-1.22 1.157-1.343.226-.042.496-.085.78-.09.603-.012 1.207-.014 1.812-.01-.005-.922-.004-1.833-.003-2.744v-.467l-3.593.003-.15.032c-.16.033-.32.063-.482.092-.34.062-.66.12-.963.214-.744.231-1.305.699-1.667 1.39-.33.628-.505 1.327-.535 2.134-.033.898-.036 1.817-.038 2.706l-.002.622c0 .09-.001.333-.192.517-.19.183-.441.178-.52.18-.454-.006-.908-.004-1.364-.005h-1.005c.004.82.003 1.63.003 2.44v.772h3.075l-.003 12.03zm4.581.937h-5.541l.005-1.544V25.47h-3.036l-.03-.51c-.005-.061-.008-.114-.008-.167v-1.03c0-.9 0-1.797-.005-2.695 0-.08-.002-.322.186-.505s.44-.176.52-.18c.418.004.837.004 1.256.002.373 0 .747 0 1.121.002l.002-.382c.002-.896.004-1.823.038-2.737.035-.934.25-1.785.64-2.528.483-.92 1.233-1.544 2.229-1.854.36-.112.726-.179 1.079-.243.153-.027.306-.056.458-.087l.308-.056h4.631l-.033.576c-.003.042-.006.083-.007.123v.705c-.001 1-.002 2 .004 2.999 0 .08.002.321-.186.505-.188.182-.438.176-.52.18-.682-.008-1.366-.007-2.047.006-.214.004-.434.04-.62.074-.228.042-.369.214-.379.46-.021.561-.027 1.125-.033 1.69l-.006.566h3.859l-.547 5.08H27.39l-.004 11.357c0 .054-.002.108-.004.162l-.017.517z'/>
                                            </g>
                                        </g>
                                    </g>
                                </g>
                            </svg>


                        </div>
                    </div>


                    <div className='footer_wrapper_link'>
                        <ul>
                            <li><a href=''>Impressum</a></li>
                            <li><a href=''>Datenschutz</a></li>
                            <li><a href=''>AGB</a></li>
                        </ul>
                        <div>
                            <p>Copyright © 2025 active value GmbH - Alle Rechte vorbehalten.</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    );

};

export default Footer;
